# Generated by Django 2.0 on 2017-12-18 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='has_mordred',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='has_oberon',
            field=models.BooleanField(default=False),
        ),
    ]
