# Generated by Django 2.0 on 2017-12-18 22:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20171218_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
