# Generated by Django 2.0 on 2017-12-25 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20171221_0621'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='num_players',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
